// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website.Data;

namespace Website.Data.Migrations
{
    [DbContext(typeof(WebsiteContext))]
    partial class WebsiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Website.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT")
                        .HasColumnName("ImageFileName");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Don't even ask me what this is supposed to be.",
                            ImageName = "amazingimage.png",
                            Name = "Definitely Something",
                            Price = 1265274658.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "I have no idea why anyone would bother wanting to buy this.",
                            ImageName = "et.jpg",
                            Name = "A Copy of E.T For the Atari 2600",
                            Price = -9.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Good Boy.",
                            ImageName = "dog.png",
                            Name = "A Picture of My Dog",
                            Price = 900.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Before you ask, we do not have any other issues of Nintendo Power in stock.",
                            ImageName = "nintendopower.jpg",
                            Name = "Nintendo Power Issue #47",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "This shoelace totally belonged to Michael Jordan at one point. Trust me.",
                            ImageName = "shoelace.jpg",
                            Name = "Michael Jordan's Shoelace",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Yum.",
                            ImageName = "chocolate.png",
                            Name = "A Hershey's Chocolate Bar",
                            Price = 0.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
